version: '3.8'
services:
  api:
    build: .
    ports:
      - "5000:5000"
    networks:
      - micro-net
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_DB=users
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge

volumes:
  db-data: